name: AI Code Review

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install # Modify based on your project

    - name: Run AI code review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        node scripts/code-review.js
